name: CI/CD Backend (Monorepo)

on:
    push:
        branches: [ "main" ]
        # O "Path Filter" garante que essa pipeline só roda se mexerem no backend
        paths:
            - 'backend/**'
            - '.github/workflows/backend.yml'

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout do código
              uses: actions/checkout@v4

            # Login do DockerHub
            - name: Login no Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            # Build and Push
            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                # IMPORTANTE: Aqui definimos o contexto apenas para a pasta backend
                context: ./backend
                file: ./backend/Dockerfile
                push: true
                # Nome da imagem no DockerHub (ajuste se quiser mudar a tag)
                tags: ${{ secrets.DOCKER_USERNAME }}/blogging-escola-backend:latest